apiVersion: v1
kind: Service
metadata:
  name: rolling-update-service
  namespace: rolling-ns
spec:
  selector:
    app: online-shop
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000          # cluster internal port
      targetPort: 3000    # forwards to containerPort
      nodePort: 30003     # port outside the cluster

      



